### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by kalpeshwadekar97** [prabhat3108/UniMoniTest#1]
* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  Output:  /Users/kalpeshwadekar/Documents/Projects/Unimoni Interview Projects/UniMoniTest/app/src/main/res/layout/data_item.xml:57: error: resource drawable/tele_consult (aka com.example.unimonitest:drawable/tele_consult) not found.
  /Users/kalpeshwadekar/Documents/Projects/Unimoni Interview Projects/UniMoniTest/app/src/main/res/layout/data_item.xml:86: error: resource drawable/health_chk (aka com.example.unimonitest:drawable/health_chk) not found.
  /Users/kalpeshwadekar/Documents/Projects/Unimoni Interview Projects/UniMoniTest/app/src/main/res/layout/data_item.xml:124: error: resource drawable/medicine (aka com.example.unimonitest:drawable/medicine) not found.
  /Users/kalpeshwadekar/Documents/Projects/Unimoni Interview Projects/UniMoniTest/app/src/main/res/layout/data_item.xml:153: error: resource drawable/dental_chk (aka com.example.unimonitest:drawable/dental_chk) not found.
  /Users/kalpeshwadekar/Documents/Projects/Unimoni Interview Projects/UniMoniTest/app/src/main/res/layout/data_item.xml:191: error: resource drawable/discount_card (aka com.example.unimonitest:drawable/discount_card) not found.
  /Users/kalpeshwadekar/Documents/Projects/Unimoni Interview Projects/UniMoniTest/app/src/main/res/layout/data_item.xml:224: error: resource drawable/save_badge (aka com.example.unimonitest:drawable/save_badge) not found.

**Comment by prabhat3108** [comment]
I forgot to add the drawables. It has been added and it should build now properly
